---
permalink: protect-scw/task_install_on_multiple_remote_hosts_using_powershell_cmdlets.html 
sidebar: sidebar 
keywords: install, snapcenter 
summary: Si desea instalar el plugin de SnapCenter para Microsoft Windows en varios hosts a la vez, puede hacerlo mediante el cmdlet de PowerShell Install-SmHostPackage. 
---
= Instale el plugin de SnapCenter para Microsoft Windows en varios hosts remotos mediante cmdlets de PowerShell
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si desea instalar el plugin de SnapCenter para Microsoft Windows en varios hosts a la vez, puede hacerlo mediante el `Install-SmHostPackage` cmdlet de PowerShell.

Tiene que haber iniciado sesión en SnapCenter como usuario del dominio con derechos de administrador local en cada host en el que desee instalar los plugins.

.Pasos
. Inicie PowerShell.
. En el host del servidor de SnapCenter, establezca una sesión mediante `Open-SmConnection` el cmdlet y, a continuación, introduzca sus credenciales.
. Añada el host o el clúster independiente a SnapCenter con `Add-SmHost` el cmdlet y los parámetros requeridos.
+
La información relativa a los parámetros que se pueden utilizar con el cmdlet y sus descripciones se puede obtener ejecutando _Get-Help nombre_comando_. Alternativamente, también puede consultar la https://docs.netapp.com/us-en/snapcenter-cmdlets/index.html["Guía de referencia de cmdlets de SnapCenter Software"^].

. Instale el plugin en varios hosts mediante `Install-SmHostPackage` el cmdlet y los parámetros requeridos.
+
Puede utilizar `-skipprecheck` la opción cuando haya instalado los plugins manualmente y no desee validar si el host cumple con los requisitos para instalar el plugin.


